sudo: false
language: php

php:
  - 5.5
  - 5.6

addons:
  apt:
    packages:
    - php5-cgi
    - php5-mysql

env:
  global:
    - MODULE_NAME='svg'
    - MODULE_TEST_GROUP='svg'
    - DRUPAL_REPO='git://drupalcode.org/project/drupal.git'
    - DRUPAL_VERSION='8.0.x'
    - PHPCS_VERSION='2.4.0'
    - CODER_VERSION='8.2.5'
    - COVERALLS_VERSION='0.6.1'
    - SIMPLETEST_DB='mysql://root@127.0.0.1/drupal'

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc

  # Codesniffer.
  - composer global require squizlabs/php_codesniffer:$PHPCS_VERSION --prefer-dist

  # Coder.
  - composer global require drupal/coder:$CODER_VERSION --prefer-dist
  - ln -s ~/.composer/vendor/drupal/coder/coder_sniffer/Drupal ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/

  # Ensure the PHP environment is ready.
  - phpenv rehash

install:
  # Move the checked out module into the correct structure.
  - mkdir /tmp/$MODULE_NAME
  - mv * /tmp/$MODULE_NAME/
  - git clone --branch $DRUPAL_VERSION $DRUPAL_REPO drupal --depth 1
  - mv /tmp/$MODULE_NAME drupal/modules/

before_script:
  # Create log directory for coverage report.
  - mkdir -p build/coverage

  # This fixes a fail when install Drupal.
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Mysql might time out for long tests, increase the wait timeout.
  - mysql -e 'SET @@GLOBAL.wait_timeout=1200'

  - mysql -e 'create database drupal;'

  # Coveralls.io
  - cd $TRAVIS_BUILD_DIR/drupal/modules/$MODULE_NAME
  - composer require satooshi/php-coveralls:$COVERALLS_VERSION --prefer-dist

script:
  # Run code sniffer.
  - phpcs --report=full --standard=Drupal --ignore=vendor $TRAVIS_BUILD_DIR/drupal/modules/$MODULE_NAME

  # Run the tests.
  - phpunit --group $MODULE_TEST_GROUP --bootstrap $TRAVIS_BUILD_DIR/drupal/core/tests/bootstrap.php --coverage-text --coverage-clover=build/logs/clover.xml --debug

after_success:
  - php vendor/bin/coveralls
