sudo: false
language: php

php:
  - 5.5
  - 5.6

addons:
  apt:
    packages:
    - php5-cgi
    - php5-mysql

env:
  global:
    - MODULE_NAME='svg'
    - MODULE_TEST_GROUP='svg'
    - DRUPAL_REPO='git://drupalcode.org/project/drupal.git'
    - DRUPAL_VERSION='8.0.x'
    - PHPCS_VERSION='2.4.0'
    - CODER_VERSION='8.2.5'
    - SIMPLETEST_DB='mysql://root@127.0.0.1/drupal'

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc

  # Codesniffer.
  - composer global require squizlabs/php_codesniffer:$PHPCS_VERSION

  # Coder.
  - composer global require drupal/coder:$CODER_VERSION
  - ln -s ~/.composer/vendor/drupal/coder/coder_sniffer/Drupal ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/

  # Ensure the PHP environment is ready.
  - phpenv rehash

  # Upgrade pip
  - pip install --user --upgrade pip

  # Coverage Reports
  - pip install --user coveralls

install:
  # Move the checked out module into the correct structure.
  - mkdir /tmp/$MODULE_NAME
  - mv * /tmp/$MODULE_NAME/
  - git clone --branch $DRUPAL_VERSION $DRUPAL_REPO drupal --depth 1
  - mv /tmp/$MODULE_NAME drupal/modules/

before_script:
  # Create log directory for coverage report.
  - mkdir -p build/logs

  # This fixes a fail when install Drupal.
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Mysql might time out for long tests, increase the wait timeout.
  - mysql -e 'SET @@GLOBAL.wait_timeout=1200'

  # Install Drupal and enable the required modules (including this one).
  - mysql -e 'create database drupal;'

script:
  # Run code sniffer.
  - phpcs --report=full --standard=Drupal $TRAVIS_BUILD_DIR/drupal/modules/$MODULE_NAME

  # Run the tests.
  - cd $TRAVIS_BUILD_DIR/drupal/modules/$MODULE_NAME
  - phpunit --group $MODULE_TEST_GROUP --bootstrap $TRAVIS_BUILD_DIR/drupal/core/tests/bootstrap.php --coverage-clover=build/logs/clover.xml -v --debug

after_success:
  - coveralls
